<a href="https://colab.research.google.com/github/lilynt02-lgtm/Programming-Horizons/blob/main/Employees_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Employees
https://youtu.be/GD10MkJjyhk?si=eMhPn-570ha2F_If

Practicing project on Python with Google Colab

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('/content/Employees.csv')

In [11]:
from google.colab import drive

In [12]:
#display the first 5 rows of the dataframe = head(). We can input the number of rows that we want to display
print(df.head(10))

   EmpID     Name     City  Age   Salary Department
0    101    Alice   London   32  50000.0         HR
1    102      Bob    Paris   31  60000.0    Finance
2    103    Chris  NewYork   35  40000.0        DBA
3    104    David   London   37      NaN         IT
4    105    Emily    Paris   33  55000.0         HR
5    106     Gina    Paris   34      NaN         IT
6    107  Charlie   Boston   29  45000.0        NaN
7    108     Paul   Sydney   30  50000.0        DBA

In [13]:
#display the last 5 rows = tail()
print(df.tail())

   EmpID     Name    City  Age   Salary Department
3    104    David  London   37      NaN         IT
4    105    Emily   Paris   33  55000.0         HR
5    106     Gina   Paris   34      NaN         IT
6    107  Charlie  Boston   29  45000.0        NaN
7    108     Paul  Sydney   30  50000.0        DBA

In [14]:
#shape : how big is this dataframe
print(df.shape)
#so here we have 8 rows and 6 columns in this dataframe

(8, 6)

In [15]:
#info() : exploring the dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       8 non-null      int64
 1   Name        8 non-null      object
 2   City        8 non-null      object
 3   Age         8 non-null      int64
 4   Salary      6 non-null      float64
 5   Department  7 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 516.0+ bytes
None

In [16]:
#describe() : display statistical summerises
print(df.describe())

           EmpID       Age        Salary
count    8.00000   8.00000      6.000000
mean   104.50000  32.62500  50000.000000
std      2.44949   2.66927   7071.067812
min    101.00000  29.00000  40000.000000
25%    102.75000  30.75000  46250.000000
50%    104.50000  32.50000  50000.000000
75%    106.25000  34.25000  53750.000000
max    108.00000  37.00000  60000.000000

In [17]:
#Add new columns
df['Year of joining'] = [2016, 2017,2018,2019,2020,2021,2022,2023]
df.head()
#there are 8 values (years) because there are 8 rows

   EmpID   Name     City  Age   Salary Department  Year of joining
0    101  Alice   London   32  50000.0         HR             2016
1    102    Bob    Paris   31  60000.0    Finance             2017
2    103  Chris  NewYork   35  40000.0        DBA             2018
3    104  David   London   37      NaN         IT             2019
4    105  Emily    Paris   33  55000.0         HR             2020

In [18]:
#create/add an other column 'Bonus' correspond 10% of the Salary
df['Bonus'] = df['Salary']*0.10
df.head()

   EmpID   Name     City  Age   Salary Department  Year of joining   Bonus
0    101  Alice   London   32  50000.0         HR             2016  5000.0
1    102    Bob    Paris   31  60000.0    Finance             2017  6000.0
2    103  Chris  NewYork   35  40000.0        DBA             2018  4000.0
3    104  David   London   37      NaN         IT             2019     NaN
4    105  Emily    Paris   33  55000.0         HR             2020  5500.0

In [19]:
#Remove a column = drop()
df.drop('Year of joining', axis = 1, inplace = True)
#because all columns are along X aqual to 1. True means make the changes permanent in the dataframe
df.head()

   EmpID   Name     City  Age   Salary Department   Bonus
0    101  Alice   London   32  50000.0         HR  5000.0
1    102    Bob    Paris   31  60000.0    Finance  6000.0
2    103  Chris  NewYork   35  40000.0        DBA  4000.0
3    104  David   London   37      NaN         IT     NaN
4    105  Emily    Paris   33  55000.0         HR  5500.0

In [20]:
#Statistical operations
#Count : calculate the total
print("Total Employees : ", df['Name'].count())

#mean() : calculate the average
print("Average Salary : ", df['Salary'].mean())

#value_counts() : count the frequency of unique value a particular column
print("Department-wise Employees Count : ", df['Department'].value_counts()) #how many times a particular department appears

Total Employees :  8
Average Salary :  50000.0
Department-wise Employees Count :  Department
HR         2
DBA        2
IT         2
Finance    1
Name: count, dtype: int64

In [21]:
#Group the data : Groupby()
print("Department-wise average alaries : ",
      df.groupby('Department')['Salary'].mean())

 #the average salary of each department

Department-wise average alaries :  Department
DBA        45000.0
Finance    60000.0
HR         52500.0
IT             NaN
Name: Salary, dtype: float64

In [22]:
#Handle missing values
print(df)

   EmpID     Name     City  Age   Salary Department   Bonus
0    101    Alice   London   32  50000.0         HR  5000.0
1    102      Bob    Paris   31  60000.0    Finance  6000.0
2    103    Chris  NewYork   35  40000.0        DBA  4000.0
3    104    David   London   37      NaN         IT     NaN
4    105    Emily    Paris   33  55000.0         HR  5500.0
5    106     Gina    Paris   34      NaN         IT     NaN
6    107  Charlie   Boston   29  45000.0        NaN  4500.0
7    108     Paul   Sydney   30  50000.0        DBA  5000.0

In [23]:
#Check for the missing values in each columns
print(df.isnull().sum())

EmpID         0
Name          0
City          0
Age           0
Salary        2
Department    1
Bonus         2
dtype: int64

In [24]:
#dropping the rows with missing values
df2 = df.dropna(axis = 0, inplace = True)
print(df2)
#dropna means remove all rows from the original dataframe
#axis = 1 means column, axis = 0 means row
#inplace = True means the changes permanent, = False means the changes tempory

None

In [25]:
print(df)

   EmpID   Name     City  Age   Salary Department   Bonus
0    101  Alice   London   32  50000.0         HR  5000.0
1    102    Bob    Paris   31  60000.0    Finance  6000.0
2    103  Chris  NewYork   35  40000.0        DBA  4000.0
4    105  Emily    Paris   33  55000.0         HR  5500.0
7    108   Paul   Sydney   30  50000.0        DBA  5000.0

In [26]:
print(df.isnull().sum())

EmpID         0
Name          0
City          0
Age           0
Salary        0
Department    0
Bonus         0
dtype: int64

In [28]:
#Filling missing values : bfill() = backward filling method
df.bfill()
#all the missing values are replaced by the next value

   EmpID   Name     City  Age   Salary Department   Bonus
0    101  Alice   London   32  50000.0         HR  5000.0
1    102    Bob    Paris   31  60000.0    Finance  6000.0
2    103  Chris  NewYork   35  40000.0        DBA  4000.0
4    105  Emily    Paris   33  55000.0         HR  5500.0
7    108   Paul   Sydney   30  50000.0        DBA  5000.0